<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
 <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
 <head>
 	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
 	<title>Document</title>
 	<style>
		#main ul li{
			list-style-type: none;
			display:inline-block;
		}
 	</style>
 </head>
 <body>
 	<h1>Hello!</h1>
	<?php echo Phalcon\Tag::linkTo("signup", "Sign Up Here!")  ?>
	<div id="main">
		<ul>
			<li><a href="/phalcon/Index/index">首页</a></li>
			<li><a href="/phalcon/Product/list">产品</a></li>
			<li><a href="/phalcon/News/detail">新闻</a></li>
			<li><a href="/phalcon/Finish/test">时尚</a></li>
		</ul>
	</div>
 </body>
 </html> 


